---
title: "Plotting brains with ggplot2"
author: Lucas França
output: html_document
date: "2023-03-03"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Packages

```{r}
# install.packages("ggseg")
```

```{r}
library(tidyverse)
library(ggseg)
library(ggseg3d)
library(RColorBrewer)
```

# The tidyverse way

## Functions and pipe opperator

```{r}
a <- min(abs(count(x)))
```

Tidyverse packages introduced a novel approach to nest function:

```{r}
a <- x %>% 
  count() %>% 
  abs() %>% 
  min()
```

## Tibbles 

```{r}
tibble1 <- tibble::tibble(
  Name = c("Anne", "Matthew", "Simon"),
  Age = c(21, 18, 19),
  Vote = c(TRUE, FALSE, TRUE)
)
```

## The function mutate()

```{r}
tibble1 %>% 
  dplyr::mutate(age_sq = Age*Age)
```


# ggplot2



# A basic brain plot

```{r}
plot(dk)
```

# Now let's add some context to this plot

```{r}
dk$data %>% 
  dplyr::mutate(t1 = rnorm(90,0), 
                t1 = t1/max(abs(t1))) %>% 
  
  ggplot2::ggplot() + geom_brain(atlas = dk,
             aes(fill = t1)) + 
  scale_fill_gradientn(colours = RColorBrewer::brewer.pal(n = 11,
                                       name = 'RdBu'), 
                       limits = c(-1,1))
```

# ROIs

```{r}
someData <- tibble::tibble(
  region = rep(c("transverse temporal", "insula",
           "precentral","superior parietal"), 2), 
  p = sample(seq(0,.5,.001), 8),
  groups = c(rep("g1", 4), rep("g2", 4))
)

someData %>%
  dplyr::group_by(groups) %>%
  
  ggplot2::ggplot() +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = p)) +
  facet_wrap(~groups)
```

# 3d plots with plotly engine

```{r}
ggseg3d(atlas=dk_3d) %>% 
  remove_axes() %>% 
  pan_camera("right lateral")
```

